# GitHub Actions workflow for CI/CD with Maven, SonarQube, and AWS EC2 deployment

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Format code with spring-javaformat
      run: mvn spring-javaformat:apply

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Copy artifact to staging directory
      run: mkdir staging && cp target/*.jar staging

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=samaneh-maven -Dsonar.projectName='samaneh-maven'

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

  #   - name: Publish Artifacts    
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: Package
  #       path: staging

  #   - name: Update dependency graph
  #     uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download Artifact
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: Package
  #       path: staging

  #   - name: Set up SSH Key
  #     run: |
  #       echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key.pem
  #       chmod 600 private_key.pem

  #   - name: Deploy JAR to EC2
  #     run: |
  #       scp -o StrictHostKeyChecking=no -i private_key.pem staging/*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app.jar

  #   - name: Restart Application on EC2
  #     run: |
  #       ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
  #         pkill -f 'java -jar' || true
  #         nohup java -jar /home/ubuntu/app.jar > app.log 2>&1 &
  #       EOF
